# Generated by Django 2.2.3 on 2020-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AlterField(
            model_name='news',
            name='avatar',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
