# Generated by Django 2.2.3 on 2020-03-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200313_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='digest',
            field=models.TextField(blank=True),
        ),
    ]
